name: firebase_tracker
description: Generic Firebase analytics tracker
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_core:
  firebase_analytics:
  tracking:
    git:
      url: https://github.com/michalsuryntequiqo/flutter_modules_copy.git #git://git@github.com:Flaconi/flutter_modules
      path: tracking
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: